#include <SDL/SDL.h>
#include <SDL/SDL_image.h>

#define WIDTH 800
#define HEIGHT 600
#define SECOND 1000
#define FRAME_PER_SECOND SECOND/60
#define SPEED_PLAYER WIDTH/100
#define SPEED_PLAYER_D 3*SPEED_PLAYER/4
#define BLOCK_WIDTH 92
#define BLOCK_HEIGHT 64
#define NB_HEARTS 3
#define HEART_SIZE 50
#define PROJECTILE_SPEED 2*SPEED_PLAYER
#define PROJECTILE_LATENCY 500
